version: "3.8"
services:
  hello-world-app:
    build:
      dockerfile: ${PWD}/03-multi-stage/Dockerfile
      context: ${PWD}/03-multi-stage
    image: demo-multi-stage
    ports:
      - 3000:3000
    environment:
      PERSON_NAME: Grocery Discovery Squad
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: password
    # Volumes store your data between container upgrades
    # Recommended but not required (DHCP needs NET_ADMIN)

    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
